---
version: 2

workflows:
  version: 2
  engine_workflow:
    jobs:
      - engine_gcp_instance_up:
      - engine_gcp_instance_ansible_config:
          requires:
            - engine_gcp_instance_up
      - engine_instance_test:
          requires:
            - engine_gcp_instance_ansible_config
      - engine_gcp_instance_down:
          requires:
            - engine_instance_test

jobs:
  engine_gcp_instance_up:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"

  engine_gcp_instance_ansible_config:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"

  engine_instance_test:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"

  engine_gcp_instance_down:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"
