---
version: 2

workflows:
  version: 2
  hello_world:
    jobs:
      - null_job

jobs:
  null_job:
    docker:
      - image: ubuntu:18.10
    environment:
      ENV_VAR: "default" 
    steps:
      - run:
          command: |
            echo "my ENV_VAR is $ENV_VAR !!"

