---
version: 2

workflows:
  version: 2
  
  web_and_engine_node_workflow:
    triggers:
      - schedule:
          cron: "0 16 * * *"
          filters:
            branches:
              only: master
    jobs:
      - web_gcp_instance_up
      - engine_gcp_instance_up
      - web_instance_ansible_config:
          requires:
            - web_gcp_instance_up
      - engine_instance_ansible_config:
          requires:
            - web_instance_ansible_config
            - engine_gcp_instance_up
      - web_instance_test:
          requires:
            - web_instance_ansible_config
      - engine_instance_test:
          requires:
            - engine_instance_ansible_config
      - web_and_engine_instance_test:
          requires:
            - web_instance_ansible_config
            - engine_instance_ansible_config
      - web_gcp_instance_down:
          requires:
            - web_and_engine_instance_test
            - web_instance_test
      - engine_gcp_instance_down:
          requires:
            - web_and_engine_instance_test
            - engine_instance_test

  all_in_one_node_workflow:
    triggers:
      - schedule:
          cron: "0 16 * * *"
          filters:
            branches:
              only: master
    jobs:
      - aio_gcp_instance_up
      - aio_instance_ansible_config:
          requires:
            - aio_gcp_instance_up 
      - web_instance_test:
          requires:
            - aio_instance_ansible_config
      - engine_instance_test:
          requires:
            - aio_instance_ansible_config
      - web_and_engine_instance_test:
          requires:
            - aio_instance_ansible_config
      - aio_gcp_instance_down:
          requires:
            - web_instance_test 
            - engine_instance_test
            - web_and_engine_instance_test 
 
jobs:
  engine_gcp_instance_up:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"

  engine_instance_ansible_config:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"

  engine_instance_test:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"

  engine_gcp_instance_down:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"

  web_gcp_instance_up:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"

  web_instance_ansible_config:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"

  web_instance_test:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"

  web_gcp_instance_down:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"

  web_and_engine_instance_test:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"

  aio_gcp_instance_up:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"

  aio_instance_ansible_config:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"
  
  aio_gcp_instance_down:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"
