---
version: 2

workflows:
  version: 2
  hello_world:
    jobs:
      - null_job
      - spin_up_gcp_instance
      - config_instance_with_ansible:
          requires: 
            - spin_up_gcp_instance

jobs:
  null_job:
    docker:
      - image: ubuntu:18.10
    environment:
      ENV_VAR: "null_job" 
    steps:
      - run:
          command: |
            echo "my ENV_VAR is $ENV_VAR !!"

  spin_up_gcp_instance:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"
      - run:
          command: |
            echo "$CIRCLE_STAGE"

  config_instance_with_ansible:
    docker:
      - image: ubuntu:18.10
    steps:
      - run:
          command: |
            echo "$CIRCLE_JOB"
      - run:
          command: |
            echo "$CIRCLE_STAGE"
