---
version: 2

workflows:
  version: 2
  hello_world:
    jobs:
      - null_job
          environment:
            ENV_VAR: "hello_world"

jobs:
  null_job:
    environment:
      ENV_VAR: "default" 
    steps:
      - run:
          command: |
            echo "my ENV_VAR is $ENV_VAR !!"

